version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: tech-support-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tech-support
    volumes:
      - mongodb_data:/data/db
    networks:
      - tech-support-network

  mongo-express:
    image: mongo-express:latest
    container_name: tech-support-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - tech-support-network

volumes:
  mongodb_data:

networks:
  tech-support-network:
    driver: bridge
